# Generated by Django 4.1.2 on 2022-10-20 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Noticia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=128, verbose_name="título")),
                ("conteudo", models.TextField(verbose_name="conteúdo")),
            ],
            options={"verbose_name": "Notícia", "verbose_name_plural": "Notícias",},
        ),
    ]
